//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Petrov_Invent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainTable
    {
        public int id { get; set; }
        public int idRole { get; set; }
        public string FIO { get; set; }
        public string email { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string phoneNum { get; set; }
        public int pasSer { get; set; }
        public int pasNum { get; set; }
        public System.DateTime Birthday { get; set; }
        public Nullable<System.DateTime> lastEnter { get; set; }
        public Nullable<int> idEnter { get; set; }
        public int idGen { get; set; }
    
        public virtual Enter Enter { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Role Role { get; set; }
    }
}
